customhost = "data-of-employee.cdyewq6aufan.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "password"
customdb = "student"
custombucket = "addemplopractice"
customregion = "us-east-1"
